## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function
## makeCacheMatrix 
##    Input: Matrix  Returns a list of defined functions -- x
##    set function - lets you set/change Matrix example x$set(matrix(rnorm(16),4,4))
##        set the matrix as a 4x4 of values generated by rnorm
##    get function - returns current matrix 
##    setinverse function - Calculates the inverse of the existing matrix example x$setinverse
##    getinverse function - Returns the inverse of the existing matrix  example x$getinverse


makeCacheMatrix <- function(x = matrix()) {
   m <<-NULL
   set <<- function(y) {
      x<<-y
      m<<-NULL
   }    
   get <- function () x
   setinverse <- function(solve) m <<- solve
   getinverse <- function() m
   list(set=set,get=get,setinverse=setinverse,getinverse=getinverse)
}


## Write a short comment describing this function

## casheSolve function
## Retreives a matrix inverse from global environment(cache) If there is no
## valide cached inverse of the matrix, the one will be created and cached for
## later access if needed.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  m<- x$getinverse()
  if(!is.null(m)) {
    message("Getting cached data")
    return(m)
  }
  data <- x$get()
  m<- solve(data,...)
  x$setinverse(m)
  m
}

